sudo: false
language: perl
perl:
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
  - dzil listdeps | cpanm
  - dzil authordeps | cpanm
